### PR TITLE
New skin: Night; minimal, sexy, as I want!

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**
Removed elements that I do not need

image

### CODE REVIEW

**Comment by vitaly-zdanevich** [comment]
With artwork enabled:

image

**Comment by vitaly-zdanevich** [comment]
IMG_20220115_215235

**Comment by noscript** [comment]
Thank you for the PR, but this is essentially the Slim skin with different colors.

I plan to add 3rd party skins distribution via GitHub later. I'm sorry, I have to decline the PR.

Including and maintaining the skins in the code base is a big burden. Eventually I will need to switch to QML and therefor the less skins I need to port, the better.

**Comment by vitaly-zdanevich** [comment]
> Thank you for the PR, but this is essentially the Slim skin with different colors.

Yes, but colors are so good :(

> Including and maintaining the skins in the code base is a big burden

This is based on Slim, and I removed unused CSS and JS also, so maintenance in minimum, and I think that this is the best theme :) many users like dark and minimalism :(

**Pull request closed without merging**
